CREATE TABLE `bsr_employee` (
  `id` varchar(64) NOT NULL COMMENT '工号',
  `name` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '员工姓名',
  `dept_id` varchar(64) DEFAULT NULL COMMENT '部门号',
  `email` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮箱',
  `birthday` date DEFAULT NULL COMMENT '出生日期',
  `hire_date` date DEFAULT NULL COMMENT '入职日期',
  `nation` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '民族',
  `politics_status` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '政治面貌',
  `highest_degree_` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '最高学历',
  `marital_status` enum('未婚','已婚','离异') DEFAULT NULL COMMENT '婚姻状况:0代表未婚，1代表已婚，2代表离异',
  `mobile` varchar(128) DEFAULT NULL COMMENT '手机号',
  `current_address` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '现居住地址',
  `address` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '户籍地址',
  `nation_idcard` varchar(128) DEFAULT NULL COMMENT '中华人民共和国身份证号',
  `position_id` int(11) DEFAULT NULL COMMENT '职位号',
  `gender` enum('保密','男','女') DEFAULT NULL COMMENT '性别',
  `picture_id` varchar(300) DEFAULT NULL COMMENT '员工头像编号',
  `gmt_create` datetime DEFAULT NULL COMMENT '表创建时间',
  `gmt_modified` datetime DEFAULT NULL COMMENT '表修改时间',
  `login_name` varchar(45) DEFAULT NULL COMMENT 'OA系统登录名称',
  `social_insurance_account` varchar(128) DEFAULT NULL COMMENT '社保账号',
  `hobby` varchar(100) DEFAULT NULL COMMENT '个人爱好',
  `bank_card` varchar(80) DEFAULT NULL COMMENT '银行卡号',
  `login_status` tinyint(1) DEFAULT '0' COMMENT '登录状态，1代表已经登录，0代表没有登录。',
  `login_addr` varchar(80) DEFAULT NULL COMMENT '用户登录的主机ip地址',
  `bank_name` varchar(50) DEFAULT NULL COMMENT '银行名称',
  `login_pwd` varchar(80) DEFAULT NULL COMMENT '登录密码',
  `native_place` varchar(45) DEFAULT NULL COMMENT '籍贯',
  `edit_enable` tinyint(1) DEFAULT '0' COMMENT '关键信息是否允许员工不经审批进行编辑，默认0不允许；1允许',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=893 DEFAULT CHARSET=utf8mb4 COMMENT='贝偌偲员工表';
